UPDATE "groups" SET "part_id" = 1 WHERE "id" = 1;
UPDATE "groups" SET "part_id" = 1 WHERE "id" = 2;
UPDATE "groups" SET "part_id" = 2 WHERE "id" = 3;
UPDATE "groups" SET "part_id" = 2 WHERE "id" = 4;
UPDATE "groups" SET "part_id" = 3 WHERE "id" = 5;
UPDATE "groups" SET "part_id" = 3 WHERE "id" = 6;
UPDATE "groups" SET "part_id" = 4 WHERE "id" = 7;
UPDATE "groups" SET "part_id" = 4 WHERE "id" = 8;
UPDATE "groups" SET "part_id" = 5 WHERE "id" = 9;
UPDATE "groups" SET "part_id" = 5 WHERE "id" = 10;
UPDATE "groups" SET "part_id" = 6 WHERE "id" = 11;
UPDATE "groups" SET "part_id" = 6 WHERE "id" = 12;
UPDATE "groups" SET "part_id" = 7 WHERE "id" = 13;
UPDATE "groups" SET "part_id" = 7 WHERE "id" = 14;
UPDATE "groups" SET "part_id" = 8 WHERE "id" = 15;
UPDATE "groups" SET "part_id" = 8 WHERE "id" = 16;
UPDATE "groups" SET "part_id" = 9 WHERE "id" = 17;
UPDATE "groups" SET "part_id" = 9 WHERE "id" = 18;
UPDATE "groups" SET "part_id" = 10 WHERE "id" = 19;
UPDATE "groups" SET "part_id" = 10 WHERE "id" = 20;
UPDATE "groups" SET "part_id" = 11 WHERE "id" = 21;
UPDATE "groups" SET "part_id" = 11 WHERE "id" = 22;
UPDATE "groups" SET "part_id" = 12 WHERE "id" = 23;
UPDATE "groups" SET "part_id" = 12 WHERE "id" = 24;
UPDATE "groups" SET "part_id" = 13 WHERE "id" = 25;
UPDATE "groups" SET "part_id" = 13 WHERE "id" = 26;
UPDATE "groups" SET "part_id" = 14 WHERE "id" = 27;
UPDATE "groups" SET "part_id" = 14 WHERE "id" = 28;
UPDATE "groups" SET "part_id" = 15 WHERE "id" = 29;
UPDATE "groups" SET "part_id" = 15 WHERE "id" = 30;
UPDATE "groups" SET "part_id" = 16 WHERE "id" = 31;
UPDATE "groups" SET "part_id" = 16 WHERE "id" = 32;
UPDATE "groups" SET "part_id" = 17 WHERE "id" = 33;
UPDATE "groups" SET "part_id" = 17 WHERE "id" = 34;
UPDATE "groups" SET "part_id" = 18 WHERE "id" = 35;
UPDATE "groups" SET "part_id" = 18 WHERE "id" = 36;
UPDATE "groups" SET "part_id" = 19 WHERE "id" = 37;
UPDATE "groups" SET "part_id" = 19 WHERE "id" = 38;
UPDATE "groups" SET "part_id" = 20 WHERE "id" = 39;
UPDATE "groups" SET "part_id" = 20 WHERE "id" = 40;
UPDATE "groups" SET "part_id" = 21 WHERE "id" = 41;
UPDATE "groups" SET "part_id" = 21 WHERE "id" = 42;
UPDATE "groups" SET "part_id" = 22 WHERE "id" = 43;
UPDATE "groups" SET "part_id" = 22 WHERE "id" = 44;
UPDATE "groups" SET "part_id" = 23 WHERE "id" = 45;
UPDATE "groups" SET "part_id" = 23 WHERE "id" = 46;
UPDATE "groups" SET "part_id" = 24 WHERE "id" = 47;
UPDATE "groups" SET "part_id" = 24 WHERE "id" = 48;
UPDATE "groups" SET "part_id" = 25 WHERE "id" = 49;
UPDATE "groups" SET "part_id" = 25 WHERE "id" = 50;
UPDATE "groups" SET "part_id" = 26 WHERE "id" = 51;
UPDATE "groups" SET "part_id" = 26 WHERE "id" = 52;
UPDATE "groups" SET "part_id" = 27 WHERE "id" = 53;
UPDATE "groups" SET "part_id" = 27 WHERE "id" = 54;
UPDATE "groups" SET "part_id" = 28 WHERE "id" = 55;
UPDATE "groups" SET "part_id" = 28 WHERE "id" = 56;
UPDATE "groups" SET "part_id" = 29 WHERE "id" = 57;
UPDATE "groups" SET "part_id" = 29 WHERE "id" = 58;
UPDATE "groups" SET "part_id" = 30 WHERE "id" = 59;
UPDATE "groups" SET "part_id" = 30 WHERE "id" = 60;
UPDATE "quarters" SET "part_id" = 1, "group_id" = 1 WHERE "id" = 1;
UPDATE "quarters" SET "part_id" = 1, "group_id" = 1 WHERE "id" = 2;
UPDATE "quarters" SET "part_id" = 1, "group_id" = 1 WHERE "id" = 3;
UPDATE "quarters" SET "part_id" = 1, "group_id" = 1 WHERE "id" = 4;
UPDATE "quarters" SET "part_id" = 1, "group_id" = 2 WHERE "id" = 5;
UPDATE "quarters" SET "part_id" = 1, "group_id" = 2 WHERE "id" = 6;
UPDATE "quarters" SET "part_id" = 1, "group_id" = 2 WHERE "id" = 7;
UPDATE "quarters" SET "part_id" = 1, "group_id" = 2 WHERE "id" = 8;
UPDATE "quarters" SET "part_id" = 2, "group_id" = 3 WHERE "id" = 9;
UPDATE "quarters" SET "part_id" = 2, "group_id" = 3 WHERE "id" = 10;
UPDATE "quarters" SET "part_id" = 2, "group_id" = 3 WHERE "id" = 11;
UPDATE "quarters" SET "part_id" = 2, "group_id" = 3 WHERE "id" = 12;
UPDATE "quarters" SET "part_id" = 2, "group_id" = 4 WHERE "id" = 13;
UPDATE "quarters" SET "part_id" = 2, "group_id" = 4 WHERE "id" = 14;
UPDATE "quarters" SET "part_id" = 2, "group_id" = 4 WHERE "id" = 15;
UPDATE "quarters" SET "part_id" = 2, "group_id" = 4 WHERE "id" = 16;
UPDATE "quarters" SET "part_id" = 3, "group_id" = 5 WHERE "id" = 17;
UPDATE "quarters" SET "part_id" = 3, "group_id" = 5 WHERE "id" = 18;
UPDATE "quarters" SET "part_id" = 3, "group_id" = 5 WHERE "id" = 19;
UPDATE "quarters" SET "part_id" = 3, "group_id" = 5 WHERE "id" = 20;
UPDATE "quarters" SET "part_id" = 3, "group_id" = 6 WHERE "id" = 21;
UPDATE "quarters" SET "part_id" = 3, "group_id" = 6 WHERE "id" = 22;
UPDATE "quarters" SET "part_id" = 3, "group_id" = 6 WHERE "id" = 23;
UPDATE "quarters" SET "part_id" = 3, "group_id" = 6 WHERE "id" = 24;
UPDATE "quarters" SET "part_id" = 4, "group_id" = 7 WHERE "id" = 25;
UPDATE "quarters" SET "part_id" = 4, "group_id" = 7 WHERE "id" = 26;
UPDATE "quarters" SET "part_id" = 4, "group_id" = 7 WHERE "id" = 27;
UPDATE "quarters" SET "part_id" = 4, "group_id" = 7 WHERE "id" = 28;
UPDATE "quarters" SET "part_id" = 4, "group_id" = 8 WHERE "id" = 29;
UPDATE "quarters" SET "part_id" = 4, "group_id" = 8 WHERE "id" = 30;
UPDATE "quarters" SET "part_id" = 4, "group_id" = 8 WHERE "id" = 31;
UPDATE "quarters" SET "part_id" = 4, "group_id" = 8 WHERE "id" = 32;
UPDATE "quarters" SET "part_id" = 5, "group_id" = 9 WHERE "id" = 33;
UPDATE "quarters" SET "part_id" = 5, "group_id" = 9 WHERE "id" = 34;
UPDATE "quarters" SET "part_id" = 5, "group_id" = 9 WHERE "id" = 35;
UPDATE "quarters" SET "part_id" = 5, "group_id" = 9 WHERE "id" = 36;
UPDATE "quarters" SET "part_id" = 5, "group_id" = 10 WHERE "id" = 37;
UPDATE "quarters" SET "part_id" = 5, "group_id" = 10 WHERE "id" = 38;
UPDATE "quarters" SET "part_id" = 5, "group_id" = 10 WHERE "id" = 39;
UPDATE "quarters" SET "part_id" = 5, "group_id" = 10 WHERE "id" = 40;
UPDATE "quarters" SET "part_id" = 6, "group_id" = 11 WHERE "id" = 41;
UPDATE "quarters" SET "part_id" = 6, "group_id" = 11 WHERE "id" = 42;
UPDATE "quarters" SET "part_id" = 6, "group_id" = 11 WHERE "id" = 43;
UPDATE "quarters" SET "part_id" = 6, "group_id" = 11 WHERE "id" = 44;
UPDATE "quarters" SET "part_id" = 6, "group_id" = 12 WHERE "id" = 45;
UPDATE "quarters" SET "part_id" = 6, "group_id" = 12 WHERE "id" = 46;
UPDATE "quarters" SET "part_id" = 6, "group_id" = 12 WHERE "id" = 47;
UPDATE "quarters" SET "part_id" = 6, "group_id" = 12 WHERE "id" = 48;
UPDATE "quarters" SET "part_id" = 7, "group_id" = 13 WHERE "id" = 49;
UPDATE "quarters" SET "part_id" = 7, "group_id" = 13 WHERE "id" = 50;
UPDATE "quarters" SET "part_id" = 7, "group_id" = 13 WHERE "id" = 51;
UPDATE "quarters" SET "part_id" = 7, "group_id" = 13 WHERE "id" = 52;
UPDATE "quarters" SET "part_id" = 7, "group_id" = 14 WHERE "id" = 53;
UPDATE "quarters" SET "part_id" = 7, "group_id" = 14 WHERE "id" = 54;
UPDATE "quarters" SET "part_id" = 7, "group_id" = 14 WHERE "id" = 55;
UPDATE "quarters" SET "part_id" = 7, "group_id" = 14 WHERE "id" = 56;
UPDATE "quarters" SET "part_id" = 8, "group_id" = 15 WHERE "id" = 57;
UPDATE "quarters" SET "part_id" = 8, "group_id" = 15 WHERE "id" = 58;
UPDATE "quarters" SET "part_id" = 8, "group_id" = 15 WHERE "id" = 59;
UPDATE "quarters" SET "part_id" = 8, "group_id" = 15 WHERE "id" = 60;
UPDATE "quarters" SET "part_id" = 8, "group_id" = 16 WHERE "id" = 61;
UPDATE "quarters" SET "part_id" = 8, "group_id" = 16 WHERE "id" = 62;
UPDATE "quarters" SET "part_id" = 8, "group_id" = 16 WHERE "id" = 63;
UPDATE "quarters" SET "part_id" = 8, "group_id" = 16 WHERE "id" = 64;
UPDATE "quarters" SET "part_id" = 9, "group_id" = 17 WHERE "id" = 65;
UPDATE "quarters" SET "part_id" = 9, "group_id" = 17 WHERE "id" = 66;
UPDATE "quarters" SET "part_id" = 9, "group_id" = 17 WHERE "id" = 67;
UPDATE "quarters" SET "part_id" = 9, "group_id" = 17 WHERE "id" = 68;
UPDATE "quarters" SET "part_id" = 9, "group_id" = 18 WHERE "id" = 69;
UPDATE "quarters" SET "part_id" = 9, "group_id" = 18 WHERE "id" = 70;
UPDATE "quarters" SET "part_id" = 9, "group_id" = 18 WHERE "id" = 71;
UPDATE "quarters" SET "part_id" = 9, "group_id" = 18 WHERE "id" = 72;
UPDATE "quarters" SET "part_id" = 10, "group_id" = 19 WHERE "id" = 73;
UPDATE "quarters" SET "part_id" = 10, "group_id" = 19 WHERE "id" = 74;
UPDATE "quarters" SET "part_id" = 10, "group_id" = 19 WHERE "id" = 75;
UPDATE "quarters" SET "part_id" = 10, "group_id" = 19 WHERE "id" = 76;
UPDATE "quarters" SET "part_id" = 10, "group_id" = 20 WHERE "id" = 77;
UPDATE "quarters" SET "part_id" = 10, "group_id" = 20 WHERE "id" = 78;
UPDATE "quarters" SET "part_id" = 10, "group_id" = 20 WHERE "id" = 79;
UPDATE "quarters" SET "part_id" = 10, "group_id" = 20 WHERE "id" = 80;
UPDATE "quarters" SET "part_id" = 11, "group_id" = 21 WHERE "id" = 81;
UPDATE "quarters" SET "part_id" = 11, "group_id" = 21 WHERE "id" = 82;
UPDATE "quarters" SET "part_id" = 11, "group_id" = 21 WHERE "id" = 83;
UPDATE "quarters" SET "part_id" = 11, "group_id" = 21 WHERE "id" = 84;
UPDATE "quarters" SET "part_id" = 11, "group_id" = 22 WHERE "id" = 85;
UPDATE "quarters" SET "part_id" = 11, "group_id" = 22 WHERE "id" = 86;
UPDATE "quarters" SET "part_id" = 11, "group_id" = 22 WHERE "id" = 87;
UPDATE "quarters" SET "part_id" = 11, "group_id" = 22 WHERE "id" = 88;
UPDATE "quarters" SET "part_id" = 12, "group_id" = 23 WHERE "id" = 89;
UPDATE "quarters" SET "part_id" = 12, "group_id" = 23 WHERE "id" = 90;
UPDATE "quarters" SET "part_id" = 12, "group_id" = 23 WHERE "id" = 91;
UPDATE "quarters" SET "part_id" = 12, "group_id" = 23 WHERE "id" = 92;
UPDATE "quarters" SET "part_id" = 12, "group_id" = 24 WHERE "id" = 93;
UPDATE "quarters" SET "part_id" = 12, "group_id" = 24 WHERE "id" = 94;
UPDATE "quarters" SET "part_id" = 12, "group_id" = 24 WHERE "id" = 95;
UPDATE "quarters" SET "part_id" = 12, "group_id" = 24 WHERE "id" = 96;
UPDATE "quarters" SET "part_id" = 13, "group_id" = 25 WHERE "id" = 97;
UPDATE "quarters" SET "part_id" = 13, "group_id" = 25 WHERE "id" = 98;
UPDATE "quarters" SET "part_id" = 13, "group_id" = 25 WHERE "id" = 99;
UPDATE "quarters" SET "part_id" = 13, "group_id" = 25 WHERE "id" = 100;
UPDATE "quarters" SET "part_id" = 13, "group_id" = 26 WHERE "id" = 101;
UPDATE "quarters" SET "part_id" = 13, "group_id" = 26 WHERE "id" = 102;
UPDATE "quarters" SET "part_id" = 13, "group_id" = 26 WHERE "id" = 103;
UPDATE "quarters" SET "part_id" = 13, "group_id" = 26 WHERE "id" = 104;
UPDATE "quarters" SET "part_id" = 14, "group_id" = 27 WHERE "id" = 105;
UPDATE "quarters" SET "part_id" = 14, "group_id" = 27 WHERE "id" = 106;
UPDATE "quarters" SET "part_id" = 14, "group_id" = 27 WHERE "id" = 107;
UPDATE "quarters" SET "part_id" = 14, "group_id" = 27 WHERE "id" = 108;
UPDATE "quarters" SET "part_id" = 14, "group_id" = 28 WHERE "id" = 109;
UPDATE "quarters" SET "part_id" = 14, "group_id" = 28 WHERE "id" = 110;
UPDATE "quarters" SET "part_id" = 14, "group_id" = 28 WHERE "id" = 111;
UPDATE "quarters" SET "part_id" = 14, "group_id" = 28 WHERE "id" = 112;
UPDATE "quarters" SET "part_id" = 15, "group_id" = 29 WHERE "id" = 113;
UPDATE "quarters" SET "part_id" = 15, "group_id" = 29 WHERE "id" = 114;
UPDATE "quarters" SET "part_id" = 15, "group_id" = 29 WHERE "id" = 115;
UPDATE "quarters" SET "part_id" = 15, "group_id" = 29 WHERE "id" = 116;
UPDATE "quarters" SET "part_id" = 15, "group_id" = 30 WHERE "id" = 117;
UPDATE "quarters" SET "part_id" = 15, "group_id" = 30 WHERE "id" = 118;
UPDATE "quarters" SET "part_id" = 15, "group_id" = 30 WHERE "id" = 119;
UPDATE "quarters" SET "part_id" = 15, "group_id" = 30 WHERE "id" = 120;
UPDATE "quarters" SET "part_id" = 16, "group_id" = 31 WHERE "id" = 121;
UPDATE "quarters" SET "part_id" = 16, "group_id" = 31 WHERE "id" = 122;
UPDATE "quarters" SET "part_id" = 16, "group_id" = 31 WHERE "id" = 123;
UPDATE "quarters" SET "part_id" = 16, "group_id" = 31 WHERE "id" = 124;
UPDATE "quarters" SET "part_id" = 16, "group_id" = 32 WHERE "id" = 125;
UPDATE "quarters" SET "part_id" = 16, "group_id" = 32 WHERE "id" = 126;
UPDATE "quarters" SET "part_id" = 16, "group_id" = 32 WHERE "id" = 127;
UPDATE "quarters" SET "part_id" = 16, "group_id" = 32 WHERE "id" = 128;
UPDATE "quarters" SET "part_id" = 17, "group_id" = 33 WHERE "id" = 129;
UPDATE "quarters" SET "part_id" = 17, "group_id" = 33 WHERE "id" = 130;
UPDATE "quarters" SET "part_id" = 17, "group_id" = 33 WHERE "id" = 131;
UPDATE "quarters" SET "part_id" = 17, "group_id" = 33 WHERE "id" = 132;
UPDATE "quarters" SET "part_id" = 17, "group_id" = 34 WHERE "id" = 133;
UPDATE "quarters" SET "part_id" = 17, "group_id" = 34 WHERE "id" = 134;
UPDATE "quarters" SET "part_id" = 17, "group_id" = 34 WHERE "id" = 135;
UPDATE "quarters" SET "part_id" = 17, "group_id" = 34 WHERE "id" = 136;
UPDATE "quarters" SET "part_id" = 18, "group_id" = 35 WHERE "id" = 137;
UPDATE "quarters" SET "part_id" = 18, "group_id" = 35 WHERE "id" = 138;
UPDATE "quarters" SET "part_id" = 18, "group_id" = 35 WHERE "id" = 139;
UPDATE "quarters" SET "part_id" = 18, "group_id" = 35 WHERE "id" = 140;
UPDATE "quarters" SET "part_id" = 18, "group_id" = 36 WHERE "id" = 141;
UPDATE "quarters" SET "part_id" = 18, "group_id" = 36 WHERE "id" = 142;
UPDATE "quarters" SET "part_id" = 18, "group_id" = 36 WHERE "id" = 143;
UPDATE "quarters" SET "part_id" = 18, "group_id" = 36 WHERE "id" = 144;
UPDATE "quarters" SET "part_id" = 19, "group_id" = 37 WHERE "id" = 145;
UPDATE "quarters" SET "part_id" = 19, "group_id" = 37 WHERE "id" = 146;
UPDATE "quarters" SET "part_id" = 19, "group_id" = 37 WHERE "id" = 147;
UPDATE "quarters" SET "part_id" = 19, "group_id" = 37 WHERE "id" = 148;
UPDATE "quarters" SET "part_id" = 19, "group_id" = 38 WHERE "id" = 149;
UPDATE "quarters" SET "part_id" = 19, "group_id" = 38 WHERE "id" = 150;
UPDATE "quarters" SET "part_id" = 19, "group_id" = 38 WHERE "id" = 151;
UPDATE "quarters" SET "part_id" = 19, "group_id" = 38 WHERE "id" = 152;
UPDATE "quarters" SET "part_id" = 20, "group_id" = 39 WHERE "id" = 153;
UPDATE "quarters" SET "part_id" = 20, "group_id" = 39 WHERE "id" = 154;
UPDATE "quarters" SET "part_id" = 20, "group_id" = 39 WHERE "id" = 155;
UPDATE "quarters" SET "part_id" = 20, "group_id" = 39 WHERE "id" = 156;
UPDATE "quarters" SET "part_id" = 20, "group_id" = 40 WHERE "id" = 157;
UPDATE "quarters" SET "part_id" = 20, "group_id" = 40 WHERE "id" = 158;
UPDATE "quarters" SET "part_id" = 20, "group_id" = 40 WHERE "id" = 159;
UPDATE "quarters" SET "part_id" = 20, "group_id" = 40 WHERE "id" = 160;
UPDATE "quarters" SET "part_id" = 21, "group_id" = 41 WHERE "id" = 161;
UPDATE "quarters" SET "part_id" = 21, "group_id" = 41 WHERE "id" = 162;
UPDATE "quarters" SET "part_id" = 21, "group_id" = 41 WHERE "id" = 163;
UPDATE "quarters" SET "part_id" = 21, "group_id" = 41 WHERE "id" = 164;
UPDATE "quarters" SET "part_id" = 21, "group_id" = 42 WHERE "id" = 165;
UPDATE "quarters" SET "part_id" = 21, "group_id" = 42 WHERE "id" = 166;
UPDATE "quarters" SET "part_id" = 21, "group_id" = 42 WHERE "id" = 167;
UPDATE "quarters" SET "part_id" = 21, "group_id" = 42 WHERE "id" = 168;
UPDATE "quarters" SET "part_id" = 22, "group_id" = 43 WHERE "id" = 169;
UPDATE "quarters" SET "part_id" = 22, "group_id" = 43 WHERE "id" = 170;
UPDATE "quarters" SET "part_id" = 22, "group_id" = 43 WHERE "id" = 171;
UPDATE "quarters" SET "part_id" = 22, "group_id" = 43 WHERE "id" = 172;
UPDATE "quarters" SET "part_id" = 22, "group_id" = 44 WHERE "id" = 173;
UPDATE "quarters" SET "part_id" = 22, "group_id" = 44 WHERE "id" = 174;
UPDATE "quarters" SET "part_id" = 22, "group_id" = 44 WHERE "id" = 175;
UPDATE "quarters" SET "part_id" = 22, "group_id" = 44 WHERE "id" = 176;
UPDATE "quarters" SET "part_id" = 23, "group_id" = 45 WHERE "id" = 177;
UPDATE "quarters" SET "part_id" = 23, "group_id" = 45 WHERE "id" = 178;
UPDATE "quarters" SET "part_id" = 23, "group_id" = 45 WHERE "id" = 179;
UPDATE "quarters" SET "part_id" = 23, "group_id" = 45 WHERE "id" = 180;
UPDATE "quarters" SET "part_id" = 23, "group_id" = 46 WHERE "id" = 181;
UPDATE "quarters" SET "part_id" = 23, "group_id" = 46 WHERE "id" = 182;
UPDATE "quarters" SET "part_id" = 23, "group_id" = 46 WHERE "id" = 183;
UPDATE "quarters" SET "part_id" = 23, "group_id" = 46 WHERE "id" = 184;
UPDATE "quarters" SET "part_id" = 24, "group_id" = 47 WHERE "id" = 185;
UPDATE "quarters" SET "part_id" = 24, "group_id" = 47 WHERE "id" = 186;
UPDATE "quarters" SET "part_id" = 24, "group_id" = 47 WHERE "id" = 187;
UPDATE "quarters" SET "part_id" = 24, "group_id" = 47 WHERE "id" = 188;
UPDATE "quarters" SET "part_id" = 24, "group_id" = 48 WHERE "id" = 189;
UPDATE "quarters" SET "part_id" = 24, "group_id" = 48 WHERE "id" = 190;
UPDATE "quarters" SET "part_id" = 24, "group_id" = 48 WHERE "id" = 191;
UPDATE "quarters" SET "part_id" = 24, "group_id" = 48 WHERE "id" = 192;
UPDATE "quarters" SET "part_id" = 25, "group_id" = 49 WHERE "id" = 193;
UPDATE "quarters" SET "part_id" = 25, "group_id" = 49 WHERE "id" = 194;
UPDATE "quarters" SET "part_id" = 25, "group_id" = 49 WHERE "id" = 195;
UPDATE "quarters" SET "part_id" = 25, "group_id" = 49 WHERE "id" = 196;
UPDATE "quarters" SET "part_id" = 25, "group_id" = 50 WHERE "id" = 197;
UPDATE "quarters" SET "part_id" = 25, "group_id" = 50 WHERE "id" = 198;
UPDATE "quarters" SET "part_id" = 25, "group_id" = 50 WHERE "id" = 199;
UPDATE "quarters" SET "part_id" = 25, "group_id" = 50 WHERE "id" = 200;
UPDATE "quarters" SET "part_id" = 26, "group_id" = 51 WHERE "id" = 201;
UPDATE "quarters" SET "part_id" = 26, "group_id" = 51 WHERE "id" = 202;
UPDATE "quarters" SET "part_id" = 26, "group_id" = 51 WHERE "id" = 203;
UPDATE "quarters" SET "part_id" = 26, "group_id" = 51 WHERE "id" = 204;
UPDATE "quarters" SET "part_id" = 26, "group_id" = 52 WHERE "id" = 205;
UPDATE "quarters" SET "part_id" = 26, "group_id" = 52 WHERE "id" = 206;
UPDATE "quarters" SET "part_id" = 26, "group_id" = 52 WHERE "id" = 207;
UPDATE "quarters" SET "part_id" = 26, "group_id" = 52 WHERE "id" = 208;
UPDATE "quarters" SET "part_id" = 27, "group_id" = 53 WHERE "id" = 209;
UPDATE "quarters" SET "part_id" = 27, "group_id" = 53 WHERE "id" = 210;
UPDATE "quarters" SET "part_id" = 27, "group_id" = 53 WHERE "id" = 211;
UPDATE "quarters" SET "part_id" = 27, "group_id" = 53 WHERE "id" = 212;
UPDATE "quarters" SET "part_id" = 27, "group_id" = 54 WHERE "id" = 213;
UPDATE "quarters" SET "part_id" = 27, "group_id" = 54 WHERE "id" = 214;
UPDATE "quarters" SET "part_id" = 27, "group_id" = 54 WHERE "id" = 215;
UPDATE "quarters" SET "part_id" = 27, "group_id" = 54 WHERE "id" = 216;
UPDATE "quarters" SET "part_id" = 28, "group_id" = 55 WHERE "id" = 217;
UPDATE "quarters" SET "part_id" = 28, "group_id" = 55 WHERE "id" = 218;
UPDATE "quarters" SET "part_id" = 28, "group_id" = 55 WHERE "id" = 219;
UPDATE "quarters" SET "part_id" = 28, "group_id" = 55 WHERE "id" = 220;
UPDATE "quarters" SET "part_id" = 28, "group_id" = 56 WHERE "id" = 221;
UPDATE "quarters" SET "part_id" = 28, "group_id" = 56 WHERE "id" = 222;
UPDATE "quarters" SET "part_id" = 28, "group_id" = 56 WHERE "id" = 223;
UPDATE "quarters" SET "part_id" = 28, "group_id" = 56 WHERE "id" = 224;
UPDATE "quarters" SET "part_id" = 29, "group_id" = 57 WHERE "id" = 225;
UPDATE "quarters" SET "part_id" = 29, "group_id" = 57 WHERE "id" = 226;
UPDATE "quarters" SET "part_id" = 29, "group_id" = 57 WHERE "id" = 227;
UPDATE "quarters" SET "part_id" = 29, "group_id" = 57 WHERE "id" = 228;
UPDATE "quarters" SET "part_id" = 29, "group_id" = 58 WHERE "id" = 229;
UPDATE "quarters" SET "part_id" = 29, "group_id" = 58 WHERE "id" = 230;
UPDATE "quarters" SET "part_id" = 29, "group_id" = 58 WHERE "id" = 231;
UPDATE "quarters" SET "part_id" = 29, "group_id" = 58 WHERE "id" = 232;
UPDATE "quarters" SET "part_id" = 30, "group_id" = 59 WHERE "id" = 233;
UPDATE "quarters" SET "part_id" = 30, "group_id" = 59 WHERE "id" = 234;
UPDATE "quarters" SET "part_id" = 30, "group_id" = 59 WHERE "id" = 235;
UPDATE "quarters" SET "part_id" = 30, "group_id" = 59 WHERE "id" = 236;
UPDATE "quarters" SET "part_id" = 30, "group_id" = 60 WHERE "id" = 237;
UPDATE "quarters" SET "part_id" = 30, "group_id" = 60 WHERE "id" = 238;
UPDATE "quarters" SET "part_id" = 30, "group_id" = 60 WHERE "id" = 239;
UPDATE "quarters" SET "part_id" = 30, "group_id" = 60 WHERE "id" = 240;
UPDATE "pages" SET "chapter_id" = 1, "part_id" = 1, "group_id" = 1, "quarter_id" = 1 WHERE "id" = 1;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 1, "quarter_id" = 1 WHERE "id" = 2;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 1, "quarter_id" = 1 WHERE "id" = 3;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 1, "quarter_id" = 1 WHERE "id" = 4;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 1, "quarter_id" = 1 WHERE "id" = 5;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 1, "quarter_id" = 2 WHERE "id" = 6;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 1, "quarter_id" = 2 WHERE "id" = 7;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 1, "quarter_id" = 3 WHERE "id" = 8;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 1, "quarter_id" = 3 WHERE "id" = 9;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 1, "quarter_id" = 4 WHERE "id" = 10;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 1, "quarter_id" = 4 WHERE "id" = 11;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 2, "quarter_id" = 5 WHERE "id" = 12;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 2, "quarter_id" = 5 WHERE "id" = 13;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 2, "quarter_id" = 5 WHERE "id" = 14;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 2, "quarter_id" = 6 WHERE "id" = 15;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 2, "quarter_id" = 6 WHERE "id" = 16;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 2, "quarter_id" = 7 WHERE "id" = 17;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 2, "quarter_id" = 7 WHERE "id" = 18;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 2, "quarter_id" = 7 WHERE "id" = 19;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 2, "quarter_id" = 8 WHERE "id" = 20;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 1, "group_id" = 2, "quarter_id" = 8 WHERE "id" = 21;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 3, "quarter_id" = 9 WHERE "id" = 22;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 3, "quarter_id" = 9 WHERE "id" = 23;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 3, "quarter_id" = 9 WHERE "id" = 24;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 3, "quarter_id" = 10 WHERE "id" = 25;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 3, "quarter_id" = 10 WHERE "id" = 26;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 3, "quarter_id" = 11 WHERE "id" = 27;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 3, "quarter_id" = 11 WHERE "id" = 28;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 3, "quarter_id" = 11 WHERE "id" = 29;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 3, "quarter_id" = 12 WHERE "id" = 30;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 3, "quarter_id" = 12 WHERE "id" = 31;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 4, "quarter_id" = 13 WHERE "id" = 32;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 4, "quarter_id" = 13 WHERE "id" = 33;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 4, "quarter_id" = 13 WHERE "id" = 34;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 4, "quarter_id" = 14 WHERE "id" = 35;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 4, "quarter_id" = 14 WHERE "id" = 36;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 4, "quarter_id" = 14 WHERE "id" = 37;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 4, "quarter_id" = 15 WHERE "id" = 38;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 4, "quarter_id" = 15 WHERE "id" = 39;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 4, "quarter_id" = 16 WHERE "id" = 40;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 2, "group_id" = 4, "quarter_id" = 16 WHERE "id" = 41;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 3, "group_id" = 5, "quarter_id" = 17 WHERE "id" = 42;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 3, "group_id" = 5, "quarter_id" = 17 WHERE "id" = 43;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 3, "group_id" = 5, "quarter_id" = 17 WHERE "id" = 44;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 3, "group_id" = 5, "quarter_id" = 18 WHERE "id" = 45;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 3, "group_id" = 5, "quarter_id" = 18 WHERE "id" = 46;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 3, "group_id" = 5, "quarter_id" = 19 WHERE "id" = 47;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 3, "group_id" = 5, "quarter_id" = 19 WHERE "id" = 48;
UPDATE "pages" SET "chapter_id" = 2, "part_id" = 3, "group_id" = 5, "quarter_id" = 20 WHERE "id" = 49;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 5, "quarter_id" = 20 WHERE "id" = 50;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 5, "quarter_id" = 20 WHERE "id" = 51;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 6, "quarter_id" = 21 WHERE "id" = 52;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 6, "quarter_id" = 21 WHERE "id" = 53;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 6, "quarter_id" = 21 WHERE "id" = 54;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 6, "quarter_id" = 22 WHERE "id" = 55;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 6, "quarter_id" = 22 WHERE "id" = 56;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 6, "quarter_id" = 23 WHERE "id" = 57;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 6, "quarter_id" = 23 WHERE "id" = 58;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 6, "quarter_id" = 23 WHERE "id" = 59;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 6, "quarter_id" = 24 WHERE "id" = 60;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 6, "quarter_id" = 24 WHERE "id" = 61;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 3, "group_id" = 6, "quarter_id" = 24 WHERE "id" = 62;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 7, "quarter_id" = 25 WHERE "id" = 63;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 7, "quarter_id" = 25 WHERE "id" = 64;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 7, "quarter_id" = 26 WHERE "id" = 65;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 7, "quarter_id" = 26 WHERE "id" = 66;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 7, "quarter_id" = 27 WHERE "id" = 67;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 7, "quarter_id" = 27 WHERE "id" = 68;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 7, "quarter_id" = 27 WHERE "id" = 69;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 7, "quarter_id" = 28 WHERE "id" = 70;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 7, "quarter_id" = 28 WHERE "id" = 71;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 7, "quarter_id" = 28 WHERE "id" = 72;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 8, "quarter_id" = 29 WHERE "id" = 73;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 8, "quarter_id" = 29 WHERE "id" = 74;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 8, "quarter_id" = 30 WHERE "id" = 75;
UPDATE "pages" SET "chapter_id" = 3, "part_id" = 4, "group_id" = 8, "quarter_id" = 30 WHERE "id" = 76;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 4, "group_id" = 8, "quarter_id" = 31 WHERE "id" = 77;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 4, "group_id" = 8, "quarter_id" = 31 WHERE "id" = 78;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 4, "group_id" = 8, "quarter_id" = 32 WHERE "id" = 79;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 4, "group_id" = 8, "quarter_id" = 32 WHERE "id" = 80;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 4, "group_id" = 8, "quarter_id" = 32 WHERE "id" = 81;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 9, "quarter_id" = 33 WHERE "id" = 82;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 9, "quarter_id" = 33 WHERE "id" = 83;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 9, "quarter_id" = 33 WHERE "id" = 84;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 9, "quarter_id" = 34 WHERE "id" = 85;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 9, "quarter_id" = 34 WHERE "id" = 86;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 9, "quarter_id" = 34 WHERE "id" = 87;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 9, "quarter_id" = 35 WHERE "id" = 88;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 9, "quarter_id" = 35 WHERE "id" = 89;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 9, "quarter_id" = 36 WHERE "id" = 90;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 9, "quarter_id" = 36 WHERE "id" = 91;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 9, "quarter_id" = 36 WHERE "id" = 92;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 10, "quarter_id" = 37 WHERE "id" = 93;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 10, "quarter_id" = 37 WHERE "id" = 94;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 10, "quarter_id" = 38 WHERE "id" = 95;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 10, "quarter_id" = 38 WHERE "id" = 96;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 10, "quarter_id" = 39 WHERE "id" = 97;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 10, "quarter_id" = 39 WHERE "id" = 98;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 10, "quarter_id" = 39 WHERE "id" = 99;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 10, "quarter_id" = 40 WHERE "id" = 100;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 5, "group_id" = 10, "quarter_id" = 40 WHERE "id" = 101;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 6, "group_id" = 11, "quarter_id" = 41 WHERE "id" = 102;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 6, "group_id" = 11, "quarter_id" = 41 WHERE "id" = 103;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 6, "group_id" = 11, "quarter_id" = 42 WHERE "id" = 104;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 6, "group_id" = 11, "quarter_id" = 42 WHERE "id" = 105;
UPDATE "pages" SET "chapter_id" = 4, "part_id" = 6, "group_id" = 11, "quarter_id" = 42 WHERE "id" = 106;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 11, "quarter_id" = 43 WHERE "id" = 107;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 11, "quarter_id" = 43 WHERE "id" = 108;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 11, "quarter_id" = 43 WHERE "id" = 109;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 11, "quarter_id" = 44 WHERE "id" = 110;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 11, "quarter_id" = 44 WHERE "id" = 111;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 11, "quarter_id" = 44 WHERE "id" = 112;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 12, "quarter_id" = 45 WHERE "id" = 113;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 12, "quarter_id" = 45 WHERE "id" = 114;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 12, "quarter_id" = 46 WHERE "id" = 115;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 12, "quarter_id" = 46 WHERE "id" = 116;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 12, "quarter_id" = 47 WHERE "id" = 117;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 12, "quarter_id" = 47 WHERE "id" = 118;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 12, "quarter_id" = 47 WHERE "id" = 119;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 12, "quarter_id" = 48 WHERE "id" = 120;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 6, "group_id" = 12, "quarter_id" = 48 WHERE "id" = 121;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 7, "group_id" = 13, "quarter_id" = 49 WHERE "id" = 122;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 7, "group_id" = 13, "quarter_id" = 49 WHERE "id" = 123;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 7, "group_id" = 13, "quarter_id" = 49 WHERE "id" = 124;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 7, "group_id" = 13, "quarter_id" = 50 WHERE "id" = 125;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 7, "group_id" = 13, "quarter_id" = 51 WHERE "id" = 126;
UPDATE "pages" SET "chapter_id" = 5, "part_id" = 7, "group_id" = 13, "quarter_id" = 51 WHERE "id" = 127;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 13, "quarter_id" = 51 WHERE "id" = 128;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 13, "quarter_id" = 51 WHERE "id" = 129;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 13, "quarter_id" = 52 WHERE "id" = 130;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 13, "quarter_id" = 52 WHERE "id" = 131;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 14, "quarter_id" = 53 WHERE "id" = 132;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 14, "quarter_id" = 53 WHERE "id" = 133;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 14, "quarter_id" = 53 WHERE "id" = 134;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 14, "quarter_id" = 54 WHERE "id" = 135;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 14, "quarter_id" = 54 WHERE "id" = 136;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 14, "quarter_id" = 55 WHERE "id" = 137;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 14, "quarter_id" = 55 WHERE "id" = 138;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 14, "quarter_id" = 55 WHERE "id" = 139;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 14, "quarter_id" = 56 WHERE "id" = 140;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 7, "group_id" = 14, "quarter_id" = 56 WHERE "id" = 141;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 8, "group_id" = 15, "quarter_id" = 57 WHERE "id" = 142;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 8, "group_id" = 15, "quarter_id" = 57 WHERE "id" = 143;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 8, "group_id" = 15, "quarter_id" = 57 WHERE "id" = 144;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 8, "group_id" = 15, "quarter_id" = 58 WHERE "id" = 145;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 8, "group_id" = 15, "quarter_id" = 58 WHERE "id" = 146;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 8, "group_id" = 15, "quarter_id" = 59 WHERE "id" = 147;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 8, "group_id" = 15, "quarter_id" = 59 WHERE "id" = 148;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 8, "group_id" = 15, "quarter_id" = 60 WHERE "id" = 149;
UPDATE "pages" SET "chapter_id" = 6, "part_id" = 8, "group_id" = 15, "quarter_id" = 60 WHERE "id" = 150;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 8, "group_id" = 16, "quarter_id" = 61 WHERE "id" = 151;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 8, "group_id" = 16, "quarter_id" = 61 WHERE "id" = 152;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 8, "group_id" = 16, "quarter_id" = 61 WHERE "id" = 153;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 8, "group_id" = 16, "quarter_id" = 62 WHERE "id" = 154;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 8, "group_id" = 16, "quarter_id" = 62 WHERE "id" = 155;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 8, "group_id" = 16, "quarter_id" = 62 WHERE "id" = 156;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 8, "group_id" = 16, "quarter_id" = 63 WHERE "id" = 157;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 8, "group_id" = 16, "quarter_id" = 63 WHERE "id" = 158;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 8, "group_id" = 16, "quarter_id" = 64 WHERE "id" = 159;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 8, "group_id" = 16, "quarter_id" = 64 WHERE "id" = 160;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 8, "group_id" = 16, "quarter_id" = 64 WHERE "id" = 161;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 17, "quarter_id" = 65 WHERE "id" = 162;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 17, "quarter_id" = 65 WHERE "id" = 163;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 17, "quarter_id" = 65 WHERE "id" = 164;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 17, "quarter_id" = 66 WHERE "id" = 165;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 17, "quarter_id" = 66 WHERE "id" = 166;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 17, "quarter_id" = 66 WHERE "id" = 167;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 17, "quarter_id" = 67 WHERE "id" = 168;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 17, "quarter_id" = 67 WHERE "id" = 169;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 17, "quarter_id" = 68 WHERE "id" = 170;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 17, "quarter_id" = 68 WHERE "id" = 171;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 17, "quarter_id" = 68 WHERE "id" = 172;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 18, "quarter_id" = 69 WHERE "id" = 173;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 18, "quarter_id" = 69 WHERE "id" = 174;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 18, "quarter_id" = 69 WHERE "id" = 175;
UPDATE "pages" SET "chapter_id" = 7, "part_id" = 9, "group_id" = 18, "quarter_id" = 70 WHERE "id" = 176;
UPDATE "pages" SET "chapter_id" = 8, "part_id" = 9, "group_id" = 18, "quarter_id" = 71 WHERE "id" = 177;
UPDATE "pages" SET "chapter_id" = 8, "part_id" = 9, "group_id" = 18, "quarter_id" = 71 WHERE "id" = 178;
UPDATE "pages" SET "chapter_id" = 8, "part_id" = 9, "group_id" = 18, "quarter_id" = 71 WHERE "id" = 179;
UPDATE "pages" SET "chapter_id" = 8, "part_id" = 9, "group_id" = 18, "quarter_id" = 72 WHERE "id" = 180;
UPDATE "pages" SET "chapter_id" = 8, "part_id" = 9, "group_id" = 18, "quarter_id" = 72 WHERE "id" = 181;
UPDATE "pages" SET "chapter_id" = 8, "part_id" = 10, "group_id" = 19, "quarter_id" = 73 WHERE "id" = 182;
UPDATE "pages" SET "chapter_id" = 8, "part_id" = 10, "group_id" = 19, "quarter_id" = 73 WHERE "id" = 183;
UPDATE "pages" SET "chapter_id" = 8, "part_id" = 10, "group_id" = 19, "quarter_id" = 73 WHERE "id" = 184;
UPDATE "pages" SET "chapter_id" = 8, "part_id" = 10, "group_id" = 19, "quarter_id" = 74 WHERE "id" = 185;
UPDATE "pages" SET "chapter_id" = 8, "part_id" = 10, "group_id" = 19, "quarter_id" = 74 WHERE "id" = 186;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 19, "quarter_id" = 75 WHERE "id" = 187;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 19, "quarter_id" = 75 WHERE "id" = 188;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 19, "quarter_id" = 75 WHERE "id" = 189;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 19, "quarter_id" = 76 WHERE "id" = 190;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 19, "quarter_id" = 76 WHERE "id" = 191;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 19, "quarter_id" = 76 WHERE "id" = 192;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 20, "quarter_id" = 77 WHERE "id" = 193;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 20, "quarter_id" = 77 WHERE "id" = 194;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 20, "quarter_id" = 78 WHERE "id" = 195;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 20, "quarter_id" = 78 WHERE "id" = 196;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 20, "quarter_id" = 79 WHERE "id" = 197;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 20, "quarter_id" = 79 WHERE "id" = 198;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 20, "quarter_id" = 79 WHERE "id" = 199;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 20, "quarter_id" = 80 WHERE "id" = 200;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 10, "group_id" = 20, "quarter_id" = 80 WHERE "id" = 201;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 11, "group_id" = 21, "quarter_id" = 81 WHERE "id" = 202;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 11, "group_id" = 21, "quarter_id" = 81 WHERE "id" = 203;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 11, "group_id" = 21, "quarter_id" = 81 WHERE "id" = 204;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 11, "group_id" = 21, "quarter_id" = 82 WHERE "id" = 205;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 11, "group_id" = 21, "quarter_id" = 82 WHERE "id" = 206;
UPDATE "pages" SET "chapter_id" = 9, "part_id" = 11, "group_id" = 21, "quarter_id" = 83 WHERE "id" = 207;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 21, "quarter_id" = 83 WHERE "id" = 208;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 21, "quarter_id" = 83 WHERE "id" = 209;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 21, "quarter_id" = 84 WHERE "id" = 210;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 21, "quarter_id" = 84 WHERE "id" = 211;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 22, "quarter_id" = 85 WHERE "id" = 212;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 22, "quarter_id" = 85 WHERE "id" = 213;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 22, "quarter_id" = 85 WHERE "id" = 214;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 22, "quarter_id" = 86 WHERE "id" = 215;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 22, "quarter_id" = 86 WHERE "id" = 216;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 22, "quarter_id" = 87 WHERE "id" = 217;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 22, "quarter_id" = 87 WHERE "id" = 218;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 22, "quarter_id" = 87 WHERE "id" = 219;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 22, "quarter_id" = 88 WHERE "id" = 220;
UPDATE "pages" SET "chapter_id" = 10, "part_id" = 11, "group_id" = 22, "quarter_id" = 88 WHERE "id" = 221;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 23, "quarter_id" = 89 WHERE "id" = 222;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 23, "quarter_id" = 89 WHERE "id" = 223;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 23, "quarter_id" = 89 WHERE "id" = 224;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 23, "quarter_id" = 90 WHERE "id" = 225;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 23, "quarter_id" = 90 WHERE "id" = 226;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 23, "quarter_id" = 91 WHERE "id" = 227;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 23, "quarter_id" = 91 WHERE "id" = 228;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 23, "quarter_id" = 92 WHERE "id" = 229;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 23, "quarter_id" = 92 WHERE "id" = 230;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 23, "quarter_id" = 92 WHERE "id" = 231;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 24, "quarter_id" = 93 WHERE "id" = 232;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 24, "quarter_id" = 93 WHERE "id" = 233;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 24, "quarter_id" = 94 WHERE "id" = 234;
UPDATE "pages" SET "chapter_id" = 11, "part_id" = 12, "group_id" = 24, "quarter_id" = 94 WHERE "id" = 235;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 12, "group_id" = 24, "quarter_id" = 94 WHERE "id" = 236;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 12, "group_id" = 24, "quarter_id" = 95 WHERE "id" = 237;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 12, "group_id" = 24, "quarter_id" = 95 WHERE "id" = 238;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 12, "group_id" = 24, "quarter_id" = 96 WHERE "id" = 239;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 12, "group_id" = 24, "quarter_id" = 96 WHERE "id" = 240;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 12, "group_id" = 24, "quarter_id" = 96 WHERE "id" = 241;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 13, "group_id" = 25, "quarter_id" = 97 WHERE "id" = 242;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 13, "group_id" = 25, "quarter_id" = 97 WHERE "id" = 243;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 13, "group_id" = 25, "quarter_id" = 97 WHERE "id" = 244;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 13, "group_id" = 25, "quarter_id" = 98 WHERE "id" = 245;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 13, "group_id" = 25, "quarter_id" = 98 WHERE "id" = 246;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 13, "group_id" = 25, "quarter_id" = 98 WHERE "id" = 247;
UPDATE "pages" SET "chapter_id" = 12, "part_id" = 13, "group_id" = 25, "quarter_id" = 99 WHERE "id" = 248;
UPDATE "pages" SET "chapter_id" = 13, "part_id" = 13, "group_id" = 25, "quarter_id" = 99 WHERE "id" = 249;
UPDATE "pages" SET "chapter_id" = 13, "part_id" = 13, "group_id" = 25, "quarter_id" = 100 WHERE "id" = 250;
UPDATE "pages" SET "chapter_id" = 13, "part_id" = 13, "group_id" = 25, "quarter_id" = 100 WHERE "id" = 251;
UPDATE "pages" SET "chapter_id" = 13, "part_id" = 13, "group_id" = 26, "quarter_id" = 101 WHERE "id" = 252;
UPDATE "pages" SET "chapter_id" = 13, "part_id" = 13, "group_id" = 26, "quarter_id" = 101 WHERE "id" = 253;
UPDATE "pages" SET "chapter_id" = 13, "part_id" = 13, "group_id" = 26, "quarter_id" = 102 WHERE "id" = 254;
UPDATE "pages" SET "chapter_id" = 13, "part_id" = 13, "group_id" = 26, "quarter_id" = 102 WHERE "id" = 255;
UPDATE "pages" SET "chapter_id" = 14, "part_id" = 13, "group_id" = 26, "quarter_id" = 102 WHERE "id" = 256;
UPDATE "pages" SET "chapter_id" = 14, "part_id" = 13, "group_id" = 26, "quarter_id" = 103 WHERE "id" = 257;
UPDATE "pages" SET "chapter_id" = 14, "part_id" = 13, "group_id" = 26, "quarter_id" = 103 WHERE "id" = 258;
UPDATE "pages" SET "chapter_id" = 14, "part_id" = 13, "group_id" = 26, "quarter_id" = 103 WHERE "id" = 259;
UPDATE "pages" SET "chapter_id" = 14, "part_id" = 13, "group_id" = 26, "quarter_id" = 104 WHERE "id" = 260;
UPDATE "pages" SET "chapter_id" = 14, "part_id" = 13, "group_id" = 26, "quarter_id" = 104 WHERE "id" = 261;
UPDATE "pages" SET "chapter_id" = 15, "part_id" = 14, "group_id" = 27, "quarter_id" = 105 WHERE "id" = 262;
UPDATE "pages" SET "chapter_id" = 15, "part_id" = 14, "group_id" = 27, "quarter_id" = 105 WHERE "id" = 263;
UPDATE "pages" SET "chapter_id" = 15, "part_id" = 14, "group_id" = 27, "quarter_id" = 105 WHERE "id" = 264;
UPDATE "pages" SET "chapter_id" = 15, "part_id" = 14, "group_id" = 27, "quarter_id" = 106 WHERE "id" = 265;
UPDATE "pages" SET "chapter_id" = 15, "part_id" = 14, "group_id" = 27, "quarter_id" = 106 WHERE "id" = 266;
UPDATE "pages" SET "chapter_id" = 15, "part_id" = 14, "group_id" = 27, "quarter_id" = 106 WHERE "id" = 267;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 27, "quarter_id" = 107 WHERE "id" = 268;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 27, "quarter_id" = 107 WHERE "id" = 269;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 27, "quarter_id" = 107 WHERE "id" = 270;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 27, "quarter_id" = 108 WHERE "id" = 271;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 27, "quarter_id" = 108 WHERE "id" = 272;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 28, "quarter_id" = 109 WHERE "id" = 273;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 28, "quarter_id" = 109 WHERE "id" = 274;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 28, "quarter_id" = 109 WHERE "id" = 275;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 28, "quarter_id" = 110 WHERE "id" = 276;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 28, "quarter_id" = 110 WHERE "id" = 277;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 28, "quarter_id" = 111 WHERE "id" = 278;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 28, "quarter_id" = 111 WHERE "id" = 279;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 28, "quarter_id" = 112 WHERE "id" = 280;
UPDATE "pages" SET "chapter_id" = 16, "part_id" = 14, "group_id" = 28, "quarter_id" = 112 WHERE "id" = 281;
UPDATE "pages" SET "chapter_id" = 17, "part_id" = 15, "group_id" = 29, "quarter_id" = 113 WHERE "id" = 282;
UPDATE "pages" SET "chapter_id" = 17, "part_id" = 15, "group_id" = 29, "quarter_id" = 113 WHERE "id" = 283;
UPDATE "pages" SET "chapter_id" = 17, "part_id" = 15, "group_id" = 29, "quarter_id" = 113 WHERE "id" = 284;
UPDATE "pages" SET "chapter_id" = 17, "part_id" = 15, "group_id" = 29, "quarter_id" = 114 WHERE "id" = 285;
UPDATE "pages" SET "chapter_id" = 17, "part_id" = 15, "group_id" = 29, "quarter_id" = 114 WHERE "id" = 286;
UPDATE "pages" SET "chapter_id" = 17, "part_id" = 15, "group_id" = 29, "quarter_id" = 115 WHERE "id" = 287;
UPDATE "pages" SET "chapter_id" = 17, "part_id" = 15, "group_id" = 29, "quarter_id" = 115 WHERE "id" = 288;
UPDATE "pages" SET "chapter_id" = 17, "part_id" = 15, "group_id" = 29, "quarter_id" = 115 WHERE "id" = 289;
UPDATE "pages" SET "chapter_id" = 17, "part_id" = 15, "group_id" = 29, "quarter_id" = 116 WHERE "id" = 290;
UPDATE "pages" SET "chapter_id" = 17, "part_id" = 15, "group_id" = 29, "quarter_id" = 116 WHERE "id" = 291;
UPDATE "pages" SET "chapter_id" = 17, "part_id" = 15, "group_id" = 29, "quarter_id" = 116 WHERE "id" = 292;
UPDATE "pages" SET "chapter_id" = 17, "part_id" = 15, "group_id" = 30, "quarter_id" = 117 WHERE "id" = 293;
UPDATE "pages" SET "chapter_id" = 18, "part_id" = 15, "group_id" = 30, "quarter_id" = 117 WHERE "id" = 294;
UPDATE "pages" SET "chapter_id" = 18, "part_id" = 15, "group_id" = 30, "quarter_id" = 117 WHERE "id" = 295;
UPDATE "pages" SET "chapter_id" = 18, "part_id" = 15, "group_id" = 30, "quarter_id" = 118 WHERE "id" = 296;
UPDATE "pages" SET "chapter_id" = 18, "part_id" = 15, "group_id" = 30, "quarter_id" = 118 WHERE "id" = 297;
UPDATE "pages" SET "chapter_id" = 18, "part_id" = 15, "group_id" = 30, "quarter_id" = 119 WHERE "id" = 298;
UPDATE "pages" SET "chapter_id" = 18, "part_id" = 15, "group_id" = 30, "quarter_id" = 119 WHERE "id" = 299;
UPDATE "pages" SET "chapter_id" = 18, "part_id" = 15, "group_id" = 30, "quarter_id" = 120 WHERE "id" = 300;
UPDATE "pages" SET "chapter_id" = 18, "part_id" = 15, "group_id" = 30, "quarter_id" = 120 WHERE "id" = 301;
UPDATE "pages" SET "chapter_id" = 18, "part_id" = 16, "group_id" = 31, "quarter_id" = 121 WHERE "id" = 302;
UPDATE "pages" SET "chapter_id" = 18, "part_id" = 16, "group_id" = 31, "quarter_id" = 121 WHERE "id" = 303;
UPDATE "pages" SET "chapter_id" = 18, "part_id" = 16, "group_id" = 31, "quarter_id" = 121 WHERE "id" = 304;
UPDATE "pages" SET "chapter_id" = 19, "part_id" = 16, "group_id" = 31, "quarter_id" = 122 WHERE "id" = 305;
UPDATE "pages" SET "chapter_id" = 19, "part_id" = 16, "group_id" = 31, "quarter_id" = 122 WHERE "id" = 306;
UPDATE "pages" SET "chapter_id" = 19, "part_id" = 16, "group_id" = 31, "quarter_id" = 123 WHERE "id" = 307;
UPDATE "pages" SET "chapter_id" = 19, "part_id" = 16, "group_id" = 31, "quarter_id" = 123 WHERE "id" = 308;
UPDATE "pages" SET "chapter_id" = 19, "part_id" = 16, "group_id" = 31, "quarter_id" = 123 WHERE "id" = 309;
UPDATE "pages" SET "chapter_id" = 19, "part_id" = 16, "group_id" = 31, "quarter_id" = 124 WHERE "id" = 310;
UPDATE "pages" SET "chapter_id" = 19, "part_id" = 16, "group_id" = 31, "quarter_id" = 124 WHERE "id" = 311;
UPDATE "pages" SET "chapter_id" = 19, "part_id" = 16, "group_id" = 31, "quarter_id" = 124 WHERE "id" = 312;
UPDATE "pages" SET "chapter_id" = 20, "part_id" = 16, "group_id" = 32, "quarter_id" = 125 WHERE "id" = 313;
UPDATE "pages" SET "chapter_id" = 20, "part_id" = 16, "group_id" = 32, "quarter_id" = 125 WHERE "id" = 314;
UPDATE "pages" SET "chapter_id" = 20, "part_id" = 16, "group_id" = 32, "quarter_id" = 125 WHERE "id" = 315;
UPDATE "pages" SET "chapter_id" = 20, "part_id" = 16, "group_id" = 32, "quarter_id" = 126 WHERE "id" = 316;
UPDATE "pages" SET "chapter_id" = 20, "part_id" = 16, "group_id" = 32, "quarter_id" = 126 WHERE "id" = 317;
UPDATE "pages" SET "chapter_id" = 20, "part_id" = 16, "group_id" = 32, "quarter_id" = 127 WHERE "id" = 318;
UPDATE "pages" SET "chapter_id" = 20, "part_id" = 16, "group_id" = 32, "quarter_id" = 127 WHERE "id" = 319;
UPDATE "pages" SET "chapter_id" = 20, "part_id" = 16, "group_id" = 32, "quarter_id" = 128 WHERE "id" = 320;
UPDATE "pages" SET "chapter_id" = 20, "part_id" = 16, "group_id" = 32, "quarter_id" = 128 WHERE "id" = 321;
UPDATE "pages" SET "chapter_id" = 21, "part_id" = 17, "group_id" = 33, "quarter_id" = 129 WHERE "id" = 322;
UPDATE "pages" SET "chapter_id" = 21, "part_id" = 17, "group_id" = 33, "quarter_id" = 129 WHERE "id" = 323;
UPDATE "pages" SET "chapter_id" = 21, "part_id" = 17, "group_id" = 33, "quarter_id" = 129 WHERE "id" = 324;
UPDATE "pages" SET "chapter_id" = 21, "part_id" = 17, "group_id" = 33, "quarter_id" = 130 WHERE "id" = 325;
UPDATE "pages" SET "chapter_id" = 21, "part_id" = 17, "group_id" = 33, "quarter_id" = 130 WHERE "id" = 326;
UPDATE "pages" SET "chapter_id" = 21, "part_id" = 17, "group_id" = 33, "quarter_id" = 131 WHERE "id" = 327;
UPDATE "pages" SET "chapter_id" = 21, "part_id" = 17, "group_id" = 33, "quarter_id" = 131 WHERE "id" = 328;
UPDATE "pages" SET "chapter_id" = 21, "part_id" = 17, "group_id" = 33, "quarter_id" = 131 WHERE "id" = 329;
UPDATE "pages" SET "chapter_id" = 21, "part_id" = 17, "group_id" = 33, "quarter_id" = 132 WHERE "id" = 330;
UPDATE "pages" SET "chapter_id" = 21, "part_id" = 17, "group_id" = 33, "quarter_id" = 132 WHERE "id" = 331;
UPDATE "pages" SET "chapter_id" = 22, "part_id" = 17, "group_id" = 34, "quarter_id" = 133 WHERE "id" = 332;
UPDATE "pages" SET "chapter_id" = 22, "part_id" = 17, "group_id" = 34, "quarter_id" = 133 WHERE "id" = 333;
UPDATE "pages" SET "chapter_id" = 22, "part_id" = 17, "group_id" = 34, "quarter_id" = 133 WHERE "id" = 334;
UPDATE "pages" SET "chapter_id" = 22, "part_id" = 17, "group_id" = 34, "quarter_id" = 134 WHERE "id" = 335;
UPDATE "pages" SET "chapter_id" = 22, "part_id" = 17, "group_id" = 34, "quarter_id" = 134 WHERE "id" = 336;
UPDATE "pages" SET "chapter_id" = 22, "part_id" = 17, "group_id" = 34, "quarter_id" = 135 WHERE "id" = 337;
UPDATE "pages" SET "chapter_id" = 22, "part_id" = 17, "group_id" = 34, "quarter_id" = 135 WHERE "id" = 338;
UPDATE "pages" SET "chapter_id" = 22, "part_id" = 17, "group_id" = 34, "quarter_id" = 135 WHERE "id" = 339;
UPDATE "pages" SET "chapter_id" = 22, "part_id" = 17, "group_id" = 34, "quarter_id" = 136 WHERE "id" = 340;
UPDATE "pages" SET "chapter_id" = 22, "part_id" = 17, "group_id" = 34, "quarter_id" = 136 WHERE "id" = 341;
UPDATE "pages" SET "chapter_id" = 23, "part_id" = 18, "group_id" = 35, "quarter_id" = 137 WHERE "id" = 342;
UPDATE "pages" SET "chapter_id" = 23, "part_id" = 18, "group_id" = 35, "quarter_id" = 137 WHERE "id" = 343;
UPDATE "pages" SET "chapter_id" = 23, "part_id" = 18, "group_id" = 35, "quarter_id" = 137 WHERE "id" = 344;
UPDATE "pages" SET "chapter_id" = 23, "part_id" = 18, "group_id" = 35, "quarter_id" = 138 WHERE "id" = 345;
UPDATE "pages" SET "chapter_id" = 23, "part_id" = 18, "group_id" = 35, "quarter_id" = 138 WHERE "id" = 346;
UPDATE "pages" SET "chapter_id" = 23, "part_id" = 18, "group_id" = 35, "quarter_id" = 139 WHERE "id" = 347;
UPDATE "pages" SET "chapter_id" = 23, "part_id" = 18, "group_id" = 35, "quarter_id" = 139 WHERE "id" = 348;
UPDATE "pages" SET "chapter_id" = 23, "part_id" = 18, "group_id" = 35, "quarter_id" = 139 WHERE "id" = 349;
UPDATE "pages" SET "chapter_id" = 24, "part_id" = 18, "group_id" = 35, "quarter_id" = 140 WHERE "id" = 350;
UPDATE "pages" SET "chapter_id" = 24, "part_id" = 18, "group_id" = 35, "quarter_id" = 140 WHERE "id" = 351;
UPDATE "pages" SET "chapter_id" = 24, "part_id" = 18, "group_id" = 36, "quarter_id" = 141 WHERE "id" = 352;
UPDATE "pages" SET "chapter_id" = 24, "part_id" = 18, "group_id" = 36, "quarter_id" = 141 WHERE "id" = 353;
UPDATE "pages" SET "chapter_id" = 24, "part_id" = 18, "group_id" = 36, "quarter_id" = 141 WHERE "id" = 354;
UPDATE "pages" SET "chapter_id" = 24, "part_id" = 18, "group_id" = 36, "quarter_id" = 142 WHERE "id" = 355;
UPDATE "pages" SET "chapter_id" = 24, "part_id" = 18, "group_id" = 36, "quarter_id" = 142 WHERE "id" = 356;
UPDATE "pages" SET "chapter_id" = 24, "part_id" = 18, "group_id" = 36, "quarter_id" = 143 WHERE "id" = 357;
UPDATE "pages" SET "chapter_id" = 24, "part_id" = 18, "group_id" = 36, "quarter_id" = 143 WHERE "id" = 358;
UPDATE "pages" SET "chapter_id" = 24, "part_id" = 18, "group_id" = 36, "quarter_id" = 143 WHERE "id" = 359;
UPDATE "pages" SET "chapter_id" = 25, "part_id" = 18, "group_id" = 36, "quarter_id" = 144 WHERE "id" = 360;
UPDATE "pages" SET "chapter_id" = 25, "part_id" = 18, "group_id" = 36, "quarter_id" = 144 WHERE "id" = 361;
UPDATE "pages" SET "chapter_id" = 25, "part_id" = 19, "group_id" = 37, "quarter_id" = 145 WHERE "id" = 362;
UPDATE "pages" SET "chapter_id" = 25, "part_id" = 19, "group_id" = 37, "quarter_id" = 145 WHERE "id" = 363;
UPDATE "pages" SET "chapter_id" = 25, "part_id" = 19, "group_id" = 37, "quarter_id" = 145 WHERE "id" = 364;
UPDATE "pages" SET "chapter_id" = 25, "part_id" = 19, "group_id" = 37, "quarter_id" = 146 WHERE "id" = 365;
UPDATE "pages" SET "chapter_id" = 25, "part_id" = 19, "group_id" = 37, "quarter_id" = 146 WHERE "id" = 366;
UPDATE "pages" SET "chapter_id" = 26, "part_id" = 19, "group_id" = 37, "quarter_id" = 147 WHERE "id" = 367;
UPDATE "pages" SET "chapter_id" = 26, "part_id" = 19, "group_id" = 37, "quarter_id" = 147 WHERE "id" = 368;
UPDATE "pages" SET "chapter_id" = 26, "part_id" = 19, "group_id" = 37, "quarter_id" = 147 WHERE "id" = 369;
UPDATE "pages" SET "chapter_id" = 26, "part_id" = 19, "group_id" = 37, "quarter_id" = 148 WHERE "id" = 370;
UPDATE "pages" SET "chapter_id" = 26, "part_id" = 19, "group_id" = 37, "quarter_id" = 148 WHERE "id" = 371;
UPDATE "pages" SET "chapter_id" = 26, "part_id" = 19, "group_id" = 38, "quarter_id" = 149 WHERE "id" = 372;
UPDATE "pages" SET "chapter_id" = 26, "part_id" = 19, "group_id" = 38, "quarter_id" = 149 WHERE "id" = 373;
UPDATE "pages" SET "chapter_id" = 26, "part_id" = 19, "group_id" = 38, "quarter_id" = 149 WHERE "id" = 374;
UPDATE "pages" SET "chapter_id" = 26, "part_id" = 19, "group_id" = 38, "quarter_id" = 150 WHERE "id" = 375;
UPDATE "pages" SET "chapter_id" = 26, "part_id" = 19, "group_id" = 38, "quarter_id" = 150 WHERE "id" = 376;
UPDATE "pages" SET "chapter_id" = 27, "part_id" = 19, "group_id" = 38, "quarter_id" = 151 WHERE "id" = 377;
UPDATE "pages" SET "chapter_id" = 27, "part_id" = 19, "group_id" = 38, "quarter_id" = 151 WHERE "id" = 378;
UPDATE "pages" SET "chapter_id" = 27, "part_id" = 19, "group_id" = 38, "quarter_id" = 151 WHERE "id" = 379;
UPDATE "pages" SET "chapter_id" = 27, "part_id" = 19, "group_id" = 38, "quarter_id" = 152 WHERE "id" = 380;
UPDATE "pages" SET "chapter_id" = 27, "part_id" = 19, "group_id" = 38, "quarter_id" = 152 WHERE "id" = 381;
UPDATE "pages" SET "chapter_id" = 27, "part_id" = 20, "group_id" = 39, "quarter_id" = 153 WHERE "id" = 382;
UPDATE "pages" SET "chapter_id" = 27, "part_id" = 20, "group_id" = 39, "quarter_id" = 153 WHERE "id" = 383;
UPDATE "pages" SET "chapter_id" = 27, "part_id" = 20, "group_id" = 39, "quarter_id" = 153 WHERE "id" = 384;
UPDATE "pages" SET "chapter_id" = 27, "part_id" = 20, "group_id" = 39, "quarter_id" = 154 WHERE "id" = 385;
UPDATE "pages" SET "chapter_id" = 28, "part_id" = 20, "group_id" = 39, "quarter_id" = 154 WHERE "id" = 386;
UPDATE "pages" SET "chapter_id" = 28, "part_id" = 20, "group_id" = 39, "quarter_id" = 155 WHERE "id" = 387;
UPDATE "pages" SET "chapter_id" = 28, "part_id" = 20, "group_id" = 39, "quarter_id" = 155 WHERE "id" = 388;
UPDATE "pages" SET "chapter_id" = 28, "part_id" = 20, "group_id" = 39, "quarter_id" = 156 WHERE "id" = 389;
UPDATE "pages" SET "chapter_id" = 28, "part_id" = 20, "group_id" = 39, "quarter_id" = 156 WHERE "id" = 390;
UPDATE "pages" SET "chapter_id" = 28, "part_id" = 20, "group_id" = 39, "quarter_id" = 156 WHERE "id" = 391;
UPDATE "pages" SET "chapter_id" = 28, "part_id" = 20, "group_id" = 40, "quarter_id" = 157 WHERE "id" = 392;
UPDATE "pages" SET "chapter_id" = 28, "part_id" = 20, "group_id" = 40, "quarter_id" = 157 WHERE "id" = 393;
UPDATE "pages" SET "chapter_id" = 28, "part_id" = 20, "group_id" = 40, "quarter_id" = 157 WHERE "id" = 394;
UPDATE "pages" SET "chapter_id" = 28, "part_id" = 20, "group_id" = 40, "quarter_id" = 158 WHERE "id" = 395;
UPDATE "pages" SET "chapter_id" = 28, "part_id" = 20, "group_id" = 40, "quarter_id" = 158 WHERE "id" = 396;
UPDATE "pages" SET "chapter_id" = 29, "part_id" = 20, "group_id" = 40, "quarter_id" = 159 WHERE "id" = 397;
UPDATE "pages" SET "chapter_id" = 29, "part_id" = 20, "group_id" = 40, "quarter_id" = 159 WHERE "id" = 398;
UPDATE "pages" SET "chapter_id" = 29, "part_id" = 20, "group_id" = 40, "quarter_id" = 159 WHERE "id" = 399;
UPDATE "pages" SET "chapter_id" = 29, "part_id" = 20, "group_id" = 40, "quarter_id" = 160 WHERE "id" = 400;
UPDATE "pages" SET "chapter_id" = 29, "part_id" = 20, "group_id" = 40, "quarter_id" = 160 WHERE "id" = 401;
UPDATE "pages" SET "chapter_id" = 29, "part_id" = 21, "group_id" = 41, "quarter_id" = 161 WHERE "id" = 402;
UPDATE "pages" SET "chapter_id" = 29, "part_id" = 21, "group_id" = 41, "quarter_id" = 161 WHERE "id" = 403;
UPDATE "pages" SET "chapter_id" = 29, "part_id" = 21, "group_id" = 41, "quarter_id" = 161 WHERE "id" = 404;
UPDATE "pages" SET "chapter_id" = 30, "part_id" = 21, "group_id" = 41, "quarter_id" = 162 WHERE "id" = 405;
UPDATE "pages" SET "chapter_id" = 30, "part_id" = 21, "group_id" = 41, "quarter_id" = 162 WHERE "id" = 406;
UPDATE "pages" SET "chapter_id" = 30, "part_id" = 21, "group_id" = 41, "quarter_id" = 162 WHERE "id" = 407;
UPDATE "pages" SET "chapter_id" = 30, "part_id" = 21, "group_id" = 41, "quarter_id" = 163 WHERE "id" = 408;
UPDATE "pages" SET "chapter_id" = 30, "part_id" = 21, "group_id" = 41, "quarter_id" = 163 WHERE "id" = 409;
UPDATE "pages" SET "chapter_id" = 30, "part_id" = 21, "group_id" = 41, "quarter_id" = 163 WHERE "id" = 410;
UPDATE "pages" SET "chapter_id" = 31, "part_id" = 21, "group_id" = 41, "quarter_id" = 164 WHERE "id" = 411;
UPDATE "pages" SET "chapter_id" = 31, "part_id" = 21, "group_id" = 41, "quarter_id" = 164 WHERE "id" = 412;
UPDATE "pages" SET "chapter_id" = 31, "part_id" = 21, "group_id" = 41, "quarter_id" = 164 WHERE "id" = 413;
UPDATE "pages" SET "chapter_id" = 31, "part_id" = 21, "group_id" = 42, "quarter_id" = 165 WHERE "id" = 414;
UPDATE "pages" SET "chapter_id" = 32, "part_id" = 21, "group_id" = 42, "quarter_id" = 165 WHERE "id" = 415;
UPDATE "pages" SET "chapter_id" = 32, "part_id" = 21, "group_id" = 42, "quarter_id" = 166 WHERE "id" = 416;
UPDATE "pages" SET "chapter_id" = 32, "part_id" = 21, "group_id" = 42, "quarter_id" = 166 WHERE "id" = 417;
UPDATE "pages" SET "chapter_id" = 33, "part_id" = 21, "group_id" = 42, "quarter_id" = 167 WHERE "id" = 418;
UPDATE "pages" SET "chapter_id" = 33, "part_id" = 21, "group_id" = 42, "quarter_id" = 167 WHERE "id" = 419;
UPDATE "pages" SET "chapter_id" = 33, "part_id" = 21, "group_id" = 42, "quarter_id" = 167 WHERE "id" = 420;
UPDATE "pages" SET "chapter_id" = 33, "part_id" = 21, "group_id" = 42, "quarter_id" = 168 WHERE "id" = 421;
UPDATE "pages" SET "chapter_id" = 33, "part_id" = 22, "group_id" = 43, "quarter_id" = 169 WHERE "id" = 422;
UPDATE "pages" SET "chapter_id" = 33, "part_id" = 22, "group_id" = 43, "quarter_id" = 169 WHERE "id" = 423;
UPDATE "pages" SET "chapter_id" = 33, "part_id" = 22, "group_id" = 43, "quarter_id" = 169 WHERE "id" = 424;
UPDATE "pages" SET "chapter_id" = 33, "part_id" = 22, "group_id" = 43, "quarter_id" = 170 WHERE "id" = 425;
UPDATE "pages" SET "chapter_id" = 33, "part_id" = 22, "group_id" = 43, "quarter_id" = 170 WHERE "id" = 426;
UPDATE "pages" SET "chapter_id" = 33, "part_id" = 22, "group_id" = 43, "quarter_id" = 171 WHERE "id" = 427;
UPDATE "pages" SET "chapter_id" = 34, "part_id" = 22, "group_id" = 43, "quarter_id" = 171 WHERE "id" = 428;
UPDATE "pages" SET "chapter_id" = 34, "part_id" = 22, "group_id" = 43, "quarter_id" = 171 WHERE "id" = 429;
UPDATE "pages" SET "chapter_id" = 34, "part_id" = 22, "group_id" = 43, "quarter_id" = 172 WHERE "id" = 430;
UPDATE "pages" SET "chapter_id" = 34, "part_id" = 22, "group_id" = 43, "quarter_id" = 172 WHERE "id" = 431;
UPDATE "pages" SET "chapter_id" = 34, "part_id" = 22, "group_id" = 44, "quarter_id" = 173 WHERE "id" = 432;
UPDATE "pages" SET "chapter_id" = 34, "part_id" = 22, "group_id" = 44, "quarter_id" = 173 WHERE "id" = 433;
UPDATE "pages" SET "chapter_id" = 34, "part_id" = 22, "group_id" = 44, "quarter_id" = 174 WHERE "id" = 434;
UPDATE "pages" SET "chapter_id" = 35, "part_id" = 22, "group_id" = 44, "quarter_id" = 174 WHERE "id" = 435;
UPDATE "pages" SET "chapter_id" = 35, "part_id" = 22, "group_id" = 44, "quarter_id" = 174 WHERE "id" = 436;
UPDATE "pages" SET "chapter_id" = 35, "part_id" = 22, "group_id" = 44, "quarter_id" = 175 WHERE "id" = 437;
UPDATE "pages" SET "chapter_id" = 35, "part_id" = 22, "group_id" = 44, "quarter_id" = 175 WHERE "id" = 438;
UPDATE "pages" SET "chapter_id" = 35, "part_id" = 22, "group_id" = 44, "quarter_id" = 175 WHERE "id" = 439;
UPDATE "pages" SET "chapter_id" = 35, "part_id" = 22, "group_id" = 44, "quarter_id" = 176 WHERE "id" = 440;
UPDATE "pages" SET "chapter_id" = 36, "part_id" = 22, "group_id" = 44, "quarter_id" = 176 WHERE "id" = 441;
UPDATE "pages" SET "chapter_id" = 36, "part_id" = 23, "group_id" = 45, "quarter_id" = 177 WHERE "id" = 442;
UPDATE "pages" SET "chapter_id" = 36, "part_id" = 23, "group_id" = 45, "quarter_id" = 177 WHERE "id" = 443;
UPDATE "pages" SET "chapter_id" = 36, "part_id" = 23, "group_id" = 45, "quarter_id" = 177 WHERE "id" = 444;
UPDATE "pages" SET "chapter_id" = 36, "part_id" = 23, "group_id" = 45, "quarter_id" = 178 WHERE "id" = 445;
UPDATE "pages" SET "chapter_id" = 37, "part_id" = 23, "group_id" = 45, "quarter_id" = 178 WHERE "id" = 446;
UPDATE "pages" SET "chapter_id" = 37, "part_id" = 23, "group_id" = 45, "quarter_id" = 179 WHERE "id" = 447;
UPDATE "pages" SET "chapter_id" = 37, "part_id" = 23, "group_id" = 45, "quarter_id" = 179 WHERE "id" = 448;
UPDATE "pages" SET "chapter_id" = 37, "part_id" = 23, "group_id" = 45, "quarter_id" = 179 WHERE "id" = 449;
UPDATE "pages" SET "chapter_id" = 37, "part_id" = 23, "group_id" = 45, "quarter_id" = 180 WHERE "id" = 450;
UPDATE "pages" SET "chapter_id" = 37, "part_id" = 23, "group_id" = 45, "quarter_id" = 180 WHERE "id" = 451;
UPDATE "pages" SET "chapter_id" = 37, "part_id" = 23, "group_id" = 46, "quarter_id" = 181 WHERE "id" = 452;
UPDATE "pages" SET "chapter_id" = 38, "part_id" = 23, "group_id" = 46, "quarter_id" = 181 WHERE "id" = 453;
UPDATE "pages" SET "chapter_id" = 38, "part_id" = 23, "group_id" = 46, "quarter_id" = 181 WHERE "id" = 454;
UPDATE "pages" SET "chapter_id" = 38, "part_id" = 23, "group_id" = 46, "quarter_id" = 182 WHERE "id" = 455;
UPDATE "pages" SET "chapter_id" = 38, "part_id" = 23, "group_id" = 46, "quarter_id" = 182 WHERE "id" = 456;
UPDATE "pages" SET "chapter_id" = 38, "part_id" = 23, "group_id" = 46, "quarter_id" = 183 WHERE "id" = 457;
UPDATE "pages" SET "chapter_id" = 38, "part_id" = 23, "group_id" = 46, "quarter_id" = 183 WHERE "id" = 458;
UPDATE "pages" SET "chapter_id" = 39, "part_id" = 23, "group_id" = 46, "quarter_id" = 183 WHERE "id" = 459;
UPDATE "pages" SET "chapter_id" = 39, "part_id" = 23, "group_id" = 46, "quarter_id" = 184 WHERE "id" = 460;
UPDATE "pages" SET "chapter_id" = 39, "part_id" = 23, "group_id" = 46, "quarter_id" = 184 WHERE "id" = 461;
UPDATE "pages" SET "chapter_id" = 39, "part_id" = 24, "group_id" = 47, "quarter_id" = 185 WHERE "id" = 462;
UPDATE "pages" SET "chapter_id" = 39, "part_id" = 24, "group_id" = 47, "quarter_id" = 185 WHERE "id" = 463;
UPDATE "pages" SET "chapter_id" = 39, "part_id" = 24, "group_id" = 47, "quarter_id" = 185 WHERE "id" = 464;
UPDATE "pages" SET "chapter_id" = 39, "part_id" = 24, "group_id" = 47, "quarter_id" = 186 WHERE "id" = 465;
UPDATE "pages" SET "chapter_id" = 39, "part_id" = 24, "group_id" = 47, "quarter_id" = 186 WHERE "id" = 466;
UPDATE "pages" SET "chapter_id" = 39, "part_id" = 24, "group_id" = 47, "quarter_id" = 186 WHERE "id" = 467;
UPDATE "pages" SET "chapter_id" = 40, "part_id" = 24, "group_id" = 47, "quarter_id" = 187 WHERE "id" = 468;
UPDATE "pages" SET "chapter_id" = 40, "part_id" = 24, "group_id" = 47, "quarter_id" = 187 WHERE "id" = 469;
UPDATE "pages" SET "chapter_id" = 40, "part_id" = 24, "group_id" = 47, "quarter_id" = 188 WHERE "id" = 470;
UPDATE "pages" SET "chapter_id" = 40, "part_id" = 24, "group_id" = 47, "quarter_id" = 188 WHERE "id" = 471;
UPDATE "pages" SET "chapter_id" = 40, "part_id" = 24, "group_id" = 48, "quarter_id" = 189 WHERE "id" = 472;
UPDATE "pages" SET "chapter_id" = 40, "part_id" = 24, "group_id" = 48, "quarter_id" = 189 WHERE "id" = 473;
UPDATE "pages" SET "chapter_id" = 40, "part_id" = 24, "group_id" = 48, "quarter_id" = 189 WHERE "id" = 474;
UPDATE "pages" SET "chapter_id" = 40, "part_id" = 24, "group_id" = 48, "quarter_id" = 190 WHERE "id" = 475;
UPDATE "pages" SET "chapter_id" = 40, "part_id" = 24, "group_id" = 48, "quarter_id" = 190 WHERE "id" = 476;
UPDATE "pages" SET "chapter_id" = 41, "part_id" = 24, "group_id" = 48, "quarter_id" = 190 WHERE "id" = 477;
UPDATE "pages" SET "chapter_id" = 41, "part_id" = 24, "group_id" = 48, "quarter_id" = 191 WHERE "id" = 478;
UPDATE "pages" SET "chapter_id" = 41, "part_id" = 24, "group_id" = 48, "quarter_id" = 191 WHERE "id" = 479;
UPDATE "pages" SET "chapter_id" = 41, "part_id" = 24, "group_id" = 48, "quarter_id" = 192 WHERE "id" = 480;
UPDATE "pages" SET "chapter_id" = 41, "part_id" = 24, "group_id" = 48, "quarter_id" = 192 WHERE "id" = 481;
UPDATE "pages" SET "chapter_id" = 41, "part_id" = 25, "group_id" = 49, "quarter_id" = 193 WHERE "id" = 482;
UPDATE "pages" SET "chapter_id" = 42, "part_id" = 25, "group_id" = 49, "quarter_id" = 193 WHERE "id" = 483;
UPDATE "pages" SET "chapter_id" = 42, "part_id" = 25, "group_id" = 49, "quarter_id" = 193 WHERE "id" = 484;
UPDATE "pages" SET "chapter_id" = 42, "part_id" = 25, "group_id" = 49, "quarter_id" = 194 WHERE "id" = 485;
UPDATE "pages" SET "chapter_id" = 42, "part_id" = 25, "group_id" = 49, "quarter_id" = 194 WHERE "id" = 486;
UPDATE "pages" SET "chapter_id" = 42, "part_id" = 25, "group_id" = 49, "quarter_id" = 195 WHERE "id" = 487;
UPDATE "pages" SET "chapter_id" = 42, "part_id" = 25, "group_id" = 49, "quarter_id" = 195 WHERE "id" = 488;
UPDATE "pages" SET "chapter_id" = 42, "part_id" = 25, "group_id" = 49, "quarter_id" = 196 WHERE "id" = 489;
UPDATE "pages" SET "chapter_id" = 43, "part_id" = 25, "group_id" = 49, "quarter_id" = 196 WHERE "id" = 490;
UPDATE "pages" SET "chapter_id" = 43, "part_id" = 25, "group_id" = 49, "quarter_id" = 196 WHERE "id" = 491;
UPDATE "pages" SET "chapter_id" = 43, "part_id" = 25, "group_id" = 50, "quarter_id" = 197 WHERE "id" = 492;
UPDATE "pages" SET "chapter_id" = 43, "part_id" = 25, "group_id" = 50, "quarter_id" = 197 WHERE "id" = 493;
UPDATE "pages" SET "chapter_id" = 43, "part_id" = 25, "group_id" = 50, "quarter_id" = 198 WHERE "id" = 494;
UPDATE "pages" SET "chapter_id" = 43, "part_id" = 25, "group_id" = 50, "quarter_id" = 198 WHERE "id" = 495;
UPDATE "pages" SET "chapter_id" = 44, "part_id" = 25, "group_id" = 50, "quarter_id" = 198 WHERE "id" = 496;
UPDATE "pages" SET "chapter_id" = 44, "part_id" = 25, "group_id" = 50, "quarter_id" = 199 WHERE "id" = 497;
UPDATE "pages" SET "chapter_id" = 44, "part_id" = 25, "group_id" = 50, "quarter_id" = 199 WHERE "id" = 498;
UPDATE "pages" SET "chapter_id" = 45, "part_id" = 25, "group_id" = 50, "quarter_id" = 199 WHERE "id" = 499;
UPDATE "pages" SET "chapter_id" = 45, "part_id" = 25, "group_id" = 50, "quarter_id" = 200 WHERE "id" = 500;
UPDATE "pages" SET "chapter_id" = 45, "part_id" = 25, "group_id" = 50, "quarter_id" = 200 WHERE "id" = 501;
UPDATE "pages" SET "chapter_id" = 45, "part_id" = 25, "group_id" = 50, "quarter_id" = 200 WHERE "id" = 502;
UPDATE "pages" SET "chapter_id" = 46, "part_id" = 26, "group_id" = 51, "quarter_id" = 201 WHERE "id" = 503;
UPDATE "pages" SET "chapter_id" = 46, "part_id" = 26, "group_id" = 51, "quarter_id" = 201 WHERE "id" = 504;
UPDATE "pages" SET "chapter_id" = 46, "part_id" = 26, "group_id" = 51, "quarter_id" = 202 WHERE "id" = 505;
UPDATE "pages" SET "chapter_id" = 46, "part_id" = 26, "group_id" = 51, "quarter_id" = 202 WHERE "id" = 506;
UPDATE "pages" SET "chapter_id" = 47, "part_id" = 26, "group_id" = 51, "quarter_id" = 202 WHERE "id" = 507;
UPDATE "pages" SET "chapter_id" = 47, "part_id" = 26, "group_id" = 51, "quarter_id" = 203 WHERE "id" = 508;
UPDATE "pages" SET "chapter_id" = 47, "part_id" = 26, "group_id" = 51, "quarter_id" = 203 WHERE "id" = 509;
UPDATE "pages" SET "chapter_id" = 47, "part_id" = 26, "group_id" = 51, "quarter_id" = 203 WHERE "id" = 510;
UPDATE "pages" SET "chapter_id" = 48, "part_id" = 26, "group_id" = 51, "quarter_id" = 204 WHERE "id" = 511;
UPDATE "pages" SET "chapter_id" = 48, "part_id" = 26, "group_id" = 51, "quarter_id" = 204 WHERE "id" = 512;
UPDATE "pages" SET "chapter_id" = 48, "part_id" = 26, "group_id" = 51, "quarter_id" = 204 WHERE "id" = 513;
UPDATE "pages" SET "chapter_id" = 48, "part_id" = 26, "group_id" = 52, "quarter_id" = 205 WHERE "id" = 514;
UPDATE "pages" SET "chapter_id" = 48, "part_id" = 26, "group_id" = 52, "quarter_id" = 205 WHERE "id" = 515;
UPDATE "pages" SET "chapter_id" = 49, "part_id" = 26, "group_id" = 52, "quarter_id" = 206 WHERE "id" = 516;
UPDATE "pages" SET "chapter_id" = 49, "part_id" = 26, "group_id" = 52, "quarter_id" = 206 WHERE "id" = 517;
UPDATE "pages" SET "chapter_id" = 50, "part_id" = 26, "group_id" = 52, "quarter_id" = 207 WHERE "id" = 518;
UPDATE "pages" SET "chapter_id" = 50, "part_id" = 26, "group_id" = 52, "quarter_id" = 207 WHERE "id" = 519;
UPDATE "pages" SET "chapter_id" = 50, "part_id" = 26, "group_id" = 52, "quarter_id" = 208 WHERE "id" = 520;
UPDATE "pages" SET "chapter_id" = 51, "part_id" = 26, "group_id" = 52, "quarter_id" = 208 WHERE "id" = 521;
UPDATE "pages" SET "chapter_id" = 51, "part_id" = 27, "group_id" = 53, "quarter_id" = 209 WHERE "id" = 522;
UPDATE "pages" SET "chapter_id" = 51, "part_id" = 27, "group_id" = 53, "quarter_id" = 209 WHERE "id" = 523;
UPDATE "pages" SET "chapter_id" = 52, "part_id" = 27, "group_id" = 53, "quarter_id" = 209 WHERE "id" = 524;
UPDATE "pages" SET "chapter_id" = 52, "part_id" = 27, "group_id" = 53, "quarter_id" = 210 WHERE "id" = 525;
UPDATE "pages" SET "chapter_id" = 53, "part_id" = 27, "group_id" = 53, "quarter_id" = 210 WHERE "id" = 526;
UPDATE "pages" SET "chapter_id" = 53, "part_id" = 27, "group_id" = 53, "quarter_id" = 211 WHERE "id" = 527;
UPDATE "pages" SET "chapter_id" = 53, "part_id" = 27, "group_id" = 53, "quarter_id" = 211 WHERE "id" = 528;
UPDATE "pages" SET "chapter_id" = 54, "part_id" = 27, "group_id" = 53, "quarter_id" = 211 WHERE "id" = 529;
UPDATE "pages" SET "chapter_id" = 54, "part_id" = 27, "group_id" = 53, "quarter_id" = 212 WHERE "id" = 530;
UPDATE "pages" SET "chapter_id" = 54, "part_id" = 27, "group_id" = 53, "quarter_id" = 212 WHERE "id" = 531;
UPDATE "pages" SET "chapter_id" = 55, "part_id" = 27, "group_id" = 54, "quarter_id" = 213 WHERE "id" = 532;
UPDATE "pages" SET "chapter_id" = 55, "part_id" = 27, "group_id" = 54, "quarter_id" = 213 WHERE "id" = 533;
UPDATE "pages" SET "chapter_id" = 55, "part_id" = 27, "group_id" = 54, "quarter_id" = 213 WHERE "id" = 534;
UPDATE "pages" SET "chapter_id" = 56, "part_id" = 27, "group_id" = 54, "quarter_id" = 214 WHERE "id" = 535;
UPDATE "pages" SET "chapter_id" = 56, "part_id" = 27, "group_id" = 54, "quarter_id" = 214 WHERE "id" = 536;
UPDATE "pages" SET "chapter_id" = 56, "part_id" = 27, "group_id" = 54, "quarter_id" = 215 WHERE "id" = 537;
UPDATE "pages" SET "chapter_id" = 57, "part_id" = 27, "group_id" = 54, "quarter_id" = 215 WHERE "id" = 538;
UPDATE "pages" SET "chapter_id" = 57, "part_id" = 27, "group_id" = 54, "quarter_id" = 215 WHERE "id" = 539;
UPDATE "pages" SET "chapter_id" = 57, "part_id" = 27, "group_id" = 54, "quarter_id" = 216 WHERE "id" = 540;
UPDATE "pages" SET "chapter_id" = 57, "part_id" = 27, "group_id" = 54, "quarter_id" = 216 WHERE "id" = 541;
UPDATE "pages" SET "chapter_id" = 58, "part_id" = 28, "group_id" = 55, "quarter_id" = 217 WHERE "id" = 542;
UPDATE "pages" SET "chapter_id" = 58, "part_id" = 28, "group_id" = 55, "quarter_id" = 217 WHERE "id" = 543;
UPDATE "pages" SET "chapter_id" = 58, "part_id" = 28, "group_id" = 55, "quarter_id" = 217 WHERE "id" = 544;
UPDATE "pages" SET "chapter_id" = 58, "part_id" = 28, "group_id" = 55, "quarter_id" = 218 WHERE "id" = 545;
UPDATE "pages" SET "chapter_id" = 59, "part_id" = 28, "group_id" = 55, "quarter_id" = 218 WHERE "id" = 546;
UPDATE "pages" SET "chapter_id" = 59, "part_id" = 28, "group_id" = 55, "quarter_id" = 218 WHERE "id" = 547;
UPDATE "pages" SET "chapter_id" = 59, "part_id" = 28, "group_id" = 55, "quarter_id" = 219 WHERE "id" = 548;
UPDATE "pages" SET "chapter_id" = 60, "part_id" = 28, "group_id" = 55, "quarter_id" = 219 WHERE "id" = 549;
UPDATE "pages" SET "chapter_id" = 60, "part_id" = 28, "group_id" = 55, "quarter_id" = 219 WHERE "id" = 550;
UPDATE "pages" SET "chapter_id" = 60, "part_id" = 28, "group_id" = 55, "quarter_id" = 220 WHERE "id" = 551;
UPDATE "pages" SET "chapter_id" = 61, "part_id" = 28, "group_id" = 55, "quarter_id" = 220 WHERE "id" = 552;
UPDATE "pages" SET "chapter_id" = 62, "part_id" = 28, "group_id" = 56, "quarter_id" = 221 WHERE "id" = 553;
UPDATE "pages" SET "chapter_id" = 62, "part_id" = 28, "group_id" = 56, "quarter_id" = 221 WHERE "id" = 554;
UPDATE "pages" SET "chapter_id" = 63, "part_id" = 28, "group_id" = 56, "quarter_id" = 222 WHERE "id" = 555;
UPDATE "pages" SET "chapter_id" = 64, "part_id" = 28, "group_id" = 56, "quarter_id" = 222 WHERE "id" = 556;
UPDATE "pages" SET "chapter_id" = 64, "part_id" = 28, "group_id" = 56, "quarter_id" = 222 WHERE "id" = 557;
UPDATE "pages" SET "chapter_id" = 65, "part_id" = 28, "group_id" = 56, "quarter_id" = 223 WHERE "id" = 558;
UPDATE "pages" SET "chapter_id" = 65, "part_id" = 28, "group_id" = 56, "quarter_id" = 223 WHERE "id" = 559;
UPDATE "pages" SET "chapter_id" = 66, "part_id" = 28, "group_id" = 56, "quarter_id" = 224 WHERE "id" = 560;
UPDATE "pages" SET "chapter_id" = 66, "part_id" = 28, "group_id" = 56, "quarter_id" = 224 WHERE "id" = 561;
UPDATE "pages" SET "chapter_id" = 67, "part_id" = 29, "group_id" = 57, "quarter_id" = 225 WHERE "id" = 562;
UPDATE "pages" SET "chapter_id" = 67, "part_id" = 29, "group_id" = 57, "quarter_id" = 225 WHERE "id" = 563;
UPDATE "pages" SET "chapter_id" = 67, "part_id" = 29, "group_id" = 57, "quarter_id" = 225 WHERE "id" = 564;
UPDATE "pages" SET "chapter_id" = 68, "part_id" = 29, "group_id" = 57, "quarter_id" = 226 WHERE "id" = 565;
UPDATE "pages" SET "chapter_id" = 68, "part_id" = 29, "group_id" = 57, "quarter_id" = 226 WHERE "id" = 566;
UPDATE "pages" SET "chapter_id" = 69, "part_id" = 29, "group_id" = 57, "quarter_id" = 227 WHERE "id" = 567;
UPDATE "pages" SET "chapter_id" = 69, "part_id" = 29, "group_id" = 57, "quarter_id" = 227 WHERE "id" = 568;
UPDATE "pages" SET "chapter_id" = 70, "part_id" = 29, "group_id" = 57, "quarter_id" = 227 WHERE "id" = 569;
UPDATE "pages" SET "chapter_id" = 70, "part_id" = 29, "group_id" = 57, "quarter_id" = 228 WHERE "id" = 570;
UPDATE "pages" SET "chapter_id" = 71, "part_id" = 29, "group_id" = 57, "quarter_id" = 228 WHERE "id" = 571;
UPDATE "pages" SET "chapter_id" = 72, "part_id" = 29, "group_id" = 58, "quarter_id" = 229 WHERE "id" = 572;
UPDATE "pages" SET "chapter_id" = 72, "part_id" = 29, "group_id" = 58, "quarter_id" = 229 WHERE "id" = 573;
UPDATE "pages" SET "chapter_id" = 73, "part_id" = 29, "group_id" = 58, "quarter_id" = 229 WHERE "id" = 574;
UPDATE "pages" SET "chapter_id" = 73, "part_id" = 29, "group_id" = 58, "quarter_id" = 230 WHERE "id" = 575;
UPDATE "pages" SET "chapter_id" = 74, "part_id" = 29, "group_id" = 58, "quarter_id" = 230 WHERE "id" = 576;
UPDATE "pages" SET "chapter_id" = 74, "part_id" = 29, "group_id" = 58, "quarter_id" = 230 WHERE "id" = 577;
UPDATE "pages" SET "chapter_id" = 75, "part_id" = 29, "group_id" = 58, "quarter_id" = 231 WHERE "id" = 578;
UPDATE "pages" SET "chapter_id" = 76, "part_id" = 29, "group_id" = 58, "quarter_id" = 231 WHERE "id" = 579;
UPDATE "pages" SET "chapter_id" = 76, "part_id" = 29, "group_id" = 58, "quarter_id" = 232 WHERE "id" = 580;
UPDATE "pages" SET "chapter_id" = 77, "part_id" = 29, "group_id" = 58, "quarter_id" = 232 WHERE "id" = 581;
UPDATE "pages" SET "chapter_id" = 78, "part_id" = 30, "group_id" = 59, "quarter_id" = 233 WHERE "id" = 582;
UPDATE "pages" SET "chapter_id" = 78, "part_id" = 30, "group_id" = 59, "quarter_id" = 233 WHERE "id" = 583;
UPDATE "pages" SET "chapter_id" = 79, "part_id" = 30, "group_id" = 59, "quarter_id" = 233 WHERE "id" = 584;
UPDATE "pages" SET "chapter_id" = 80, "part_id" = 30, "group_id" = 59, "quarter_id" = 234 WHERE "id" = 585;
UPDATE "pages" SET "chapter_id" = 81, "part_id" = 30, "group_id" = 59, "quarter_id" = 234 WHERE "id" = 586;
UPDATE "pages" SET "chapter_id" = 82, "part_id" = 30, "group_id" = 59, "quarter_id" = 235 WHERE "id" = 587;
UPDATE "pages" SET "chapter_id" = 83, "part_id" = 30, "group_id" = 59, "quarter_id" = 235 WHERE "id" = 588;
UPDATE "pages" SET "chapter_id" = 83, "part_id" = 30, "group_id" = 59, "quarter_id" = 235 WHERE "id" = 589;
UPDATE "pages" SET "chapter_id" = 85, "part_id" = 30, "group_id" = 59, "quarter_id" = 236 WHERE "id" = 590;
UPDATE "pages" SET "chapter_id" = 86, "part_id" = 30, "group_id" = 59, "quarter_id" = 236 WHERE "id" = 591;
UPDATE "pages" SET "chapter_id" = 87, "part_id" = 30, "group_id" = 60, "quarter_id" = 237 WHERE "id" = 592;
UPDATE "pages" SET "chapter_id" = 89, "part_id" = 30, "group_id" = 60, "quarter_id" = 237 WHERE "id" = 593;
UPDATE "pages" SET "chapter_id" = 89, "part_id" = 30, "group_id" = 60, "quarter_id" = 237 WHERE "id" = 594;
UPDATE "pages" SET "chapter_id" = 91, "part_id" = 30, "group_id" = 60, "quarter_id" = 238 WHERE "id" = 595;
UPDATE "pages" SET "chapter_id" = 92, "part_id" = 30, "group_id" = 60, "quarter_id" = 238 WHERE "id" = 596;
UPDATE "pages" SET "chapter_id" = 95, "part_id" = 30, "group_id" = 60, "quarter_id" = 239 WHERE "id" = 597;
UPDATE "pages" SET "chapter_id" = 97, "part_id" = 30, "group_id" = 60, "quarter_id" = 239 WHERE "id" = 598;
UPDATE "pages" SET "chapter_id" = 98, "part_id" = 30, "group_id" = 60, "quarter_id" = 239 WHERE "id" = 599;
UPDATE "pages" SET "chapter_id" = 100, "part_id" = 30, "group_id" = 60, "quarter_id" = 240 WHERE "id" = 600;
UPDATE "pages" SET "chapter_id" = 103, "part_id" = 30, "group_id" = 60, "quarter_id" = 240 WHERE "id" = 601;
UPDATE "pages" SET "chapter_id" = 106, "part_id" = 30, "group_id" = 60, "quarter_id" = 240 WHERE "id" = 602;
UPDATE "pages" SET "chapter_id" = 109, "part_id" = 30, "group_id" = 60, "quarter_id" = 240 WHERE "id" = 603;
UPDATE "pages" SET "chapter_id" = 112, "part_id" = 30, "group_id" = 60, "quarter_id" = 240 WHERE "id" = 604;
