# This workflow automate the generation of the data using quran-cli
# For more info: https://github.com/youzarsiph/quran-cli

name: CD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install quran-cli

      - name: Generate data
        run: |
          source .venv/bin/activate
          quran-cli init -g db.sqlite3
          quran-cli normalize -d -g db.sqlite3
          quran-cli export db.sqlite3 -o json
          rm sql/quran-db.sqlite3
          mv db.sqlite3 sql/quran-db.sqlite3

      - name: Push to repo
        run: |
          now=$(date)
          git config --global user.email "youzarsiph@quran.com"
          git config --global user.name "Yousuf Abu Shanab"
          git add .
          git commit -m "Scheduled run on $now"
          git push
